backend:
  name: test-repo
  branch: develop
publish_mode: editorial_workflow
media_folder: public/assets/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Hero Header", name: "heroHeader", widget: "string"}
        - { label: "Hero Description", name: "heroDescription", widget: "text"}
        - { label: "What We Do Header", name: "whatWeDoHeader", widget: "string"}
        - label: 'What We Do items'
          name: "whatWeDoItems"
          widget: list
          fields:
            - { label: "Header", name: "header", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Button Text", name: "buttonText", widget: "string"}
            - { label: "Button URL", name: "buttonUrl", widget: "string"}
        - { label: "View Pages Header", name: "viewPagesHeader", widget: "string"}
        - { label: "View Pages Description", name: "viewPagesDescription", widget: "text"}
        - { label: "Contact Header", name: "contactHeader", widget: "string"}
        - { label: "Contact Description", name: "contactDescription", widget: "text"}